### ISSUE TITLE
Inconsistent handling of NULL callback in cdio_paranoia_read_limited

### ISSUE THREAD

**Issue by mskamp** [rocky/libcdio-paranoia#15]
I wanted to find out whether cdio_paranoia_read_limited accepts a NULL argument for the callback parameter. The check in this line...
https://github.com/rocky/libcdio-paranoia/blob/da12cf5e76ba5dcf8b5b525dd90662af97f1bac3/lib/paranoia/paranoia.c#L3122
... made me believe that NULL arguments are dealt with correctly. However, the following call is not protected by a NULL check, which made my application crash:
https://github.com/rocky/libcdio-paranoia/blob/6591cb89c7dec1b5e9a16eb0c2fa33bb2e5b9084/lib/paranoia/paranoia.c#L2618
I think the handling of a NULL argument should be consistent here. If you do not want to support NULL arguments for the callback parameter, I'd advise to remove the first check and/or add the non-NULL requirement to the documentation.

**Comment by rocky** [comment]
Thanks for the observation and report. If you are up for putting in a pull request, things will probably get resolved faster.

Otherwise, I'll look at this in more detail and fix in due time.
