### ISSUE TITLE
Transport error when using --force-overread

### ISSUE THREAD

**Issue by jtl999** [rocky/libcdio-paranoia#17]
Drive: Samsung SH-S223L (flashed patched firmware years ago to remove DVD region code and riplock)

OS: Ubuntu 18.04 running in an LXC container due to avoid dependency problems on host, block device passthrough, this works.

CD tested: [Mark O'Connor "Heros"](https://musicbrainz.org/release/063aac03-d0d7-4e45-8cc8-a07e763398c4)

I use whipper to rip the CD's, but when testing the overread feature, after the last track of this disc, it would get stuck at ripping stage at 99%. I manually ran cd-paranoia with the same arguments as whipper used and it does rip the selected portion of the disc and then spits out "transport error" at the end.

Here was the command ran.

```
cd-paranoia --stderr-progress --sample-offset=6 --force-overread --force-cdrom-device /dev/sr0 14[00:00:00.00]-14[00:08:01.74] /tmp/tmpqeDioy.whipper.wav
```

If I remove the `sample-offset` there is no more transport error, but this imply anything useful?

Or is this whole issue implying my drive doesn't support `--force-overread` in the first place?

Thanks.

**Comment by rocky** [comment]
In issue #14 someone else reported a problem in using `--sample-offset`, and I think there is a problem in using `--force-overread` with `--sample-offset`. 

That said, I really don't have a clue as to what the right thing to do here is. @enzo1982 @eshattow ?

**Comment by jtl999** [comment]
After much more reading...

Appears to some other sources the SH-S223X series of Samsung/TSSTCorp drives don't support overread, so if that's the case then I doubt libcdio-paranoia will be of help here.

**Comment by rocky** [comment]
Is there a way to detect whether a drive supports overread? Perhaps there is a MMC command you can send to the drive to have it report that it supports or doesn't support overread?

**Comment by jtl999** [comment]
Don't know but there should be a way to detect if a drive supports overread in some form (EAC does it)

I know with the EAC tests for HTOA (similar) a yes is a maybe, a drive *can* return silence for a non-silent HTOA on a disc and EAC interprets it as supporting reading of HTOA but a no is a certain no.
