### ISSUE TITLE
10.2+2.0.0: cdio_cddap_track_audiop missing

### ISSUE THREAD

**Issue by kloczek** [rocky/libcdio-paranoia#21]
I have problem with building gvs with libcdio-paranoia.
gvfs fails with:
<pre>gcc  -o daemon/gvfsd-cdda &apos;daemon/f77b12a@@gvfsd-cdda@exe/daemon-main.c.o&apos; &apos;daemon/f77b12a@@gvfsd-cdda@exe/daemon-main-generic.c.o&apos; &apos;daemon/f77b12a@@gvfsd-cdda@exe/gvfsbackendcdda.c.o&apos; -Wl,--no-undefined -Wl,--as-needed -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -Wl,--start-group daemon/libgvfsdaemon.so common/libgvfscommon.so /usr/lib64/libgio-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libglib-2.0.so /usr/lib64/libgudev-1.0.so /usr/lib64/libcdio_paranoia.so /usr/lib64/libcdio.so -Wl,--end-group &apos;-Wl,-rpath,$ORIGIN/:$ORIGIN/../common&apos; -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/gvfs-1.42.0/x86_64-redhat-linux-gnu/daemon -Wl,-rpath-link,/home/tkloczko/rpmbuild/BUILD/gvfs-1.42.0/x86_64-redhat-linux-gnu/common
/usr/bin/ld: /tmp/gvfsd-cdda.9RGuZe.ltrans0.ltrans.o: undefined reference to symbol &apos;cdio_cddap_track_audiop&apos;
/usr/bin/ld: /usr/lib64//libcdio_cdda.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.rAf0WG (%build)
</pre>
Just checked libcdio-paranoia tree and it is something strange about only that symbol
<pre>[tkloczko@barrel libcdio-paranoia-10.2+2.0.0]$ grep -r cdio_cddap_track_audiop
<font color="#75507B">lib/cdda_interface/libcdio_cdda.sym</font><font color="#06989A">:</font><font color="#CC0000"><b>cdio_cddap_track_audiop</b></font>
<font color="#75507B">include/cdio/paranoia/cdda.h</font><font color="#06989A">:</font>extern int     <font color="#CC0000"><b>cdio_cddap_track_audiop</b></font>(cdrom_drive_t *d, track_t i_track);
<font color="#75507B">include/cdio/paranoia/cdda.h</font><font color="#06989A">:</font>#define cdda_track_audiop       <font color="#CC0000"><b>cdio_cddap_track_audiop</b></font>
</pre>
Looks like there is no actual code behind exactly that symbol.

May I ask for help or maybe it is a bug?

**Comment by kloczek** [comment]
I have modified .pc files
<pre>[tkloczko@barrel libcdio-paranoia-10.2+2.0.0]$ cat libcdio_paranoia.pc 
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: libcdio_paranoia
Description: CD paranoia library from libcdio
Version: 10.2+2.0.0
Requires: libcdio
Libs: -L${libdir} -lcdio_paranoia
Cflags: -I${includedir}/cdio

[tkloczko@barrel libcdio-paranoia-10.2+2.0.0]$ cat libcdio_cdda.pc 
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib64
includedir=/usr/include

Name: libcdio_cdda
Description: CD paranoia CD-DA library from libcdio
Version: 10.2+2.0.0
Requires: libcdio
Libs: -L${libdir} -lcdio_cdda
Cflags: -I${includedir}/cdio

</pre>
However looks like libcdio_cdda uses symbols from libcdio_paranoia and vice versa.
With such loopy dependencies looks like have two libraries does not make to much sense.

**Comment by rocky** [comment]
This is a bug.  Should be an easy fix which I'll do when I am able.

**Comment by rocky** [comment]
Please file one issue per issue. That makes it possible to track independent issues. Thanks.

**Comment by rocky** [comment]
> I have modified .pc files

The `.pc` files are derivied files. I looked over the `.pc.in` files and don't see anything I want changed. 

As for the loopiness, if you have specific suggestions feel free to make a PR for that.
