### ISSUE TITLE
Upload 10.2+2.0.1 to GNU mirrors?

### ISSUE THREAD

**Issue by nckx** [rocky/libcdio-paranoia#22]
Hullo,

I was updating the libcdio(-paranoia) packages in [GNU Guix](http://guix.gnu.org/) and noticed that [the latest release here](https://github.com/rocky/libcdio-paranoia/releases), 10.2+2.0.1, has yet to make it to https://ftp.gnu.org/pub/gnu/libcdio .

Would it be possible to upload an autoconf'd release tarball there?

These ‘archives’ that GitHub provides instead aren't very good: they're missing `./configure` and change randomly, making them impossible to verify by hashes or signatures.

Thanks!

**Comment by rocky** [comment]
Thanks for packing this on GNU Guix. 

The [GNU ftp site for libcdio](https://ftp.gnu.org/pub/gnu/libcdio/?C=M;O=D) should now have https://ftp.gnu.org/pub/gnu/libcdio/libcdio-paranoia-10.2+2.0.1.tar.gz and https://ftp.gnu.org/pub/gnu/libcdio/libcdio-paranoia-10.2+2.0.1.tar.bz2

Thanks for pointing out this omission. And yes, the archives that GitHub provide isn't very good. I am not sure how I can disable the archive portion keeping the release notes and tagging portion.

**Comment by nckx** [comment]
Nice, thank you for the quick reply! I'll close this issue & update our package soon.

> I am not sure how I can disable the archive portion keeping the release notes and tagging portion.

Neither am I…
