### ISSUE TITLE
make check fails on FreeBSD 12

### ISSUE THREAD

**Issue by boretom** [rocky/libcdio-paranoia#25]
Hi,

After compiling libcdio-paranoia on Freebsd 12 `make check` fails halfway through with
````
[...]
Making check in data
make  cdda.bin        cdda.cue        cdda2.cue
'cdda.bin' is up to date.
'cdda.cue' is up to date.
'cdda2.cue' is up to date.
make[2]: don't know how to make CFLAGS. Stop
[...]
````
**I did investigate a bit and the following is what I found:**
- compiled using FreeBSDs make, not GNU make
- tested with (tag) release-10.2+2.0.0 and later. Error does not happen in tags before (offending line didn't exist)
- FreeBSD make doesn't support target specific variables

The offending code is on line 38 in `test/Makefile.am`:
`check-am: get_libcdio_version`

For FreeBSD 12 the following works for me:
````
.if target(get_libcdio_version)
       CFLAGS += @LIBCDIO_CFLAGS@
.endif
````
Using GNU make does work just fine. I'm not a real master in autoconf oder Makefile-ery, maybe the offending line could be written in a way that works with both make?

**Comment by rocky** [comment]
Personally, I've given up going down the rabbithole of try8ing to make things work on non-GNU Make. I've devoted way too much time trying to understand the in's and out's of Make and the whole automess thing. 

GNU Make is easily available on FreeBSD, and nowadays most people install this from some sort of package of which there seem to be dozens of packages for this. So sticking to a generic make is helping those few that build from source, and would find it a chore to use GNU Make. 

That said, if someone else wants to devote the effort make this work on a generic make, go ahead. However, personally, I'd rather have any of the other existing issues solved or stuff like https://savannah.gnu.org/bugs/?57736 addressed first.

**Comment by boretom** [comment]
Hey @rocky 

I see and can understand, you got a lot more experience than I got. How about mentioning the fact of using GNU make on FreeBSD in the INSTALL file. Would that be ok?

Like under "Particular systems" add something like:

---

   On FreeBSD use GNU `make' (package `gmake`) to build. FreeBSD `make'
doesn't support all GNU `make' features and builds may fail. Install
GNU `make' on FreeBSD 10.0 and newer as follows:

    /usr/sbin/pkg install gmake

---

And I'll see if I can address an existing issue.

**Comment by rocky** [comment]
> How about mentioning the fact of using GNU make on FreeBSD in the INSTALL file. Would that be ok?

Absoutely! Please put in a PR for this. - a person who encounters a problem is in the best position to know how to best address the problem.

> And I'll see if I can address an existing issue.

Many thanks.
