### ISSUE TITLE
Wrong formatting of name section in cd-paranoia manpage

### ISSUE THREAD

**Issue by philippemilink** [rocky/libcdio-paranoia#34]
Hello,

While updating the Debian package of libcdio-paranoia, I noticed lintian raised a [bad-whatis-entry](https://lintian.debian.org/tags/bad-whatis-entry) warning for /usr/share/man/man1/cd-paranoia.1.gz. Indeed, lexgrog cannot parse it:
```
% lexgrog -d /usr/share/man/man1/cd-paranoia.1.gz
...
record = 'cd-paranoia 9.8 (Paranoia release III via libcdio) - an audio CD reading utility which includes extra data verification features'
/usr/share/man/man1/cd-paranoia.1.gz: parse failed
```

I fixed the problem by changing [this line](https://github.com/rocky/libcdio-paranoia/blob/master/doc/en/cd-paranoia.1.in#L3) to 
```
@CDPARANOIA_NAME@ \- an audio CD reading utility which includes extra data verification features (Paranoia release III via libcdio)
``` 
(it seems there can be only the binary's name the man page is about before the `\-`)

**Comment by rocky** [comment]
Thanks or the bug report and fix. It should be applied now, but if it isn't just reopen the issue.

The change needs to be made in file `libcdio-paranoia/doc/en/cd-paranoia.1.in` not `libcdio-paranoia/doc/en/cd-paranoia.1`. The former is the template file which is in giet from which the latter gets generated. The latter file is not in git. I think though the latter file may get included in a distribution tarball.
