### ISSUE TITLE
Getting garbage using MSYS2 build through pipes

### ISSUE THREAD

**Issue by donmor** [rocky/libcdio-paranoia#47]
I can get correct result using `cd-paranoia -d \\.\H: -w 3 03.wav`. But if I use `cd-paranoia -d \\.\H: -w 3 - > 03.wav`, I got a wav file filled with noise.

**Comment by rocky** [comment]
Neither the manual pages for [cd-paranoia](https://linux.die.net/man/1/cd-paranoia) nor the Linux-only [cdparanoia](https://linux.die.net/man/1/cdparanoia) indicate that one can use `-` to pass the output to stdout. 
See
