### ISSUE TITLE
Advertise this repository as official

### ISSUE THREAD

**Issue by Lapin0t** [rocky/libcdio-paranoia#6]
Hi, this may be dumb, but it would be nice to advertise this as the official repository for `libcdio-paranoia` (here in the readme but also on the website). It is extremely hard to find this repository starting from the [official page](https://www.gnu.org/software/libcdio/) and the fact that it is not hosted on savannah is quite intriguing. In fact the *only* link i could find was in [this mail](https://lists.gnu.org/archive/html/libcdio-devel/2012-10/msg00055.html) from 2012! This is quite confusing given the fact that the paranoia features and even API reference are advertised on the project's page.

**Comment by rocky** [comment]
Thanks for pointing this out.

I'll update the line when I get a chance. If you want you could download that index.html page you link and modify it suitably and I'll push it back to the right place.

**Comment by Lapin0t** [comment]
Here is an updated version [libcdio_index.html.txt](https://github.com/rocky/libcdio-paranoia/files/744465/libcdio_index.html.txt). I only added an item to the _browse source code_ section but I also took the liberty of modifying the savannah links so that they point to the cgit web interface (instead of the more crude gitweb).

**Comment by rocky** [comment]
Many thanks! It should be [updated now](https://www.gnu.org/software/libcdio/index.html)

(So no it wasn't dumb.)
